export { default as Dashboard } from './Dashboard'
export { default as HomePage } from '../HomePage'
export { default as EventDetails } from './EventDetails'
export { default as NavBar } from './NavBar'
export { default as UserEvents } from './UserEvents'
export { default as ProfilePage } from './ProfilePage'
export { default as About} from './About'
export { default as Header} from './Header'