export { default as Dashboard } from './Dashboard'
export { default as HomePage } from './HomePage'
export { default as EventDetails } from './EventDetails'
export { default as NavBar } from './NavBar'
export { default as UserEvents } from './UserEvents'
